name: Create release zip

on:
  release:
    types: [published]

permissions:
  contents: write
  
jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: Patch manifest and zip
        run: |
          sed -i 's/v0.0.0/${{ steps.version.outputs.version }}/' custom_components/dynamic_energy_contract_calculator/manifest.json
          cd custom_components/dynamic_energy_contract_calculator/
          zip ../../dynamic_energy_contract_calculator.zip -r ./
      - uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dynamic_energy_contract_calculator.zip
          asset_name: dynamic_energy_contract_calculator.zip
          tag: ${{ github.ref }}
          overwrite: true
